### ISSUE TITLE
Critical Error - puzzle

### ISSUE THREAD

**Issue by tspr** [dismine/valentina#1]
trying to open a layout. 

I get critical error - Puzzle

File error.

Exception: Can't open schema file ://schema/layout/v0.1.3.xsd:
No such file or directory.

I run Build revision: Git:7a3e37c19 
Built on Fr. Nov. 11 2022 at 19:22:12

uname -a: 
Linux  5.19.13-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Tue, 04 Oct 2022 14:37:01 +0000 x86_64 GNU/Linux
i3wm

**Comment by dismine** [comment]
This is a mirror for Valentina develop branch on GitHub and it's meant to be read-only. The main repo is https://gitlab.com/smart-pattern/valentina
