### ISSUE TITLE
Crash in save on astm and aama dxf

### ISSUE THREAD

**Issue by tspr** [dismine/valentina#2]
Trying to save (click on butteon next to cogwheel, "Export original Layout") auto layout to DXF R10 AAMA, or dxf r10 astm
valentina crashes and the window disappears

pdf saving works, dxf flat works.

I run Build revision: Git:7a3e37c19
Built on Fr. Nov. 11 2022 at 19:22:12

uname -a:
Linux 5.19.13-zen1-1-zen https://github.com/dismine/valentina/issues/1 ZEN SMP PREEMPT_DYNAMIC Tue, 04 Oct 2022 14:37:01 +0000 x86_64 GNU/Linux
i3wm

i suspect problem with schema path? Linked to https://github.com/dismine/valentina/issues/1  ???

**Comment by tspr** [comment]
Linked to https://github.com/dismine/valentina/issues/1

**Comment by dismine** [comment]
This is a mirror for Valentina develop branch on GitHub and it's meant to be read-only. The main repo is https://gitlab.com/smart-pattern/valentina
